# Generated by Django 4.1 on 2022-09-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='owasp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=4)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
    ]
